# whitelist the following branches for building
branches:
    only:
        - master
        - dev

dist: trusty
sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        # add more combinations here as per requirement
        - env: PYTHON_VERSION="3.6" NUMPY_VERSION="1.17" 
               SKLEARN_VERSION="0.21.0" TF_VERSION="1.15"

install:
    # install miniconda
    - deactivate
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - MINICONDA_PATH=/home/travis/miniconda
    - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
    - export PATH=$MINICONDA_PATH/bin:$PATH
    - conda update --yes conda

    # create the testing environment
    - conda create -n testenv --yes python=$PYTHON_VERSION pip
    - source activate testenv
    - conda install -n testenv --yes pip numpy=$NUMPY_VERSION cython nose pytest pytest-cov sphinx jupyter
    - pip install tensorflow==$TF_VERSION
    - pip install sphinx_rtd_theme
    - pip install nbsphinx
    - pip install scikit-learn==$SKLEARN_VERSION

    # install keras contrib manually as currently not available on pypi
    - pip install git+https://github.com/keras-team/keras-contrib.git@master

    # for test pypi add dependency installs manually
    # - pip install --index-url --no-deps https://test.pypi.org/simple sktime_dl==0.2.dev1
    - pip install .
    - python setup.py build_ext -i
    - pip list

script:
    - python -c "import sklearn"
    - mkdir for_test
    - cd for_test
    - pytest -v --cov=sktime_dl --pyargs ../sktime_dl




